# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkExample' do

use_frameworks!    

pod 'Alamofire'
pod 'ObjectMapper'
pod 'AlamofireObjectMapper'

end
